name: Supabase Activity Scheduler

on:
  schedule:
    - cron: "0 0 * * 0,3" # 毎週日曜日と水曜日に実行
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: curl https://kosen-ai-chatbot.vercel.app/api/etc/supabase-activity-scheduler 